# Site settings
title: Lumia
description: Groupe de Jazz & Funk à Strasbourg

exclude: ['package.json', 'src' , 'node_modules']

plugins:
  - jekyll-multiple-languages-plugin

languages: ["fr", "de"]
